import OpenAI from "openai";
import { NextRequest, NextResponse } from "next/server";

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY!,
});

export async function POST(req: NextRequest) {
  try {
    const userCookie = req.cookies.get("whop_user");
    
    if (!userCookie) {
      return NextResponse.json(
        { error: "User not authenticated" },
        { status: 401 }
      );
    }

    let user;
    try {
      user = JSON.parse(userCookie.value);
    } catch {
      return NextResponse.json(
        { error: "Invalid user data" },
        { status: 400 }
      );
    }

    const { productName, productType, website, description, style, outline } =
      await req.json();

    // Validate required fields (outline is optional)
    if (!productName || !productType || !website || !description || !style) {
      return NextResponse.json(
        { error: "Missing required fields" },
        { status: 400 }
      );
    }

    // Create the prompt for the GPT model
    const prompt = `
    Create a marketing script for the following product:
    - Product Name: ${productName}
    - Product Type: ${productType}
    - Website: ${website}
    - Description: ${description}
    - Style: ${style}
    - Outline: ${outline}

    The script might include the following sections:
    Hook:
    Intro:
    Features:
    Social Proof: 
    Call to Action:
    Conclusion:

    Provide the script in a plain text. No title, No styling. PLAIN TEXT AND ONLY USE COLONS FOR SECTIONS. BREAK TEXT BETWEEN SCETIONS.
  `;

    // Call the OpenAI API
    const response = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [
        {
          role: "system",
          content:
            "ViralifyAI is a tiktok affiliate marketing viral script generator that creates good english, viral scripts, without making stuff up, or assuming things about the product. You're the api skriptify uses.",
        },
        { role: "user", content: prompt },
      ],
      temperature: 0.92,
      max_tokens: 700,
      top_p: 0.59,
      frequency_penalty: 0,
      presence_penalty: 0.27,
    });

    const generatedText = response.choices[0].message?.content?.trim();

    if (!generatedText) {
      throw new Error("No content generated by OpenAI");
    }

    // Send the generated script via email
    const origin = req.nextUrl.origin;
    const emailResponse = await fetch(
      `${origin}/api/send`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          email: user.email,
          firstName: user.name || user.username,
          script: generatedText,
        }),
      }
    );

    if (!emailResponse.ok) {
      console.error("Failed to send email");
      // Don't fail the request if email fails, just log it
    }

    // Split the generated text into the respective parts
    const scriptParts = generatedText.split("\n\n").reduce(
      (acc: { [key: string]: string }, part: string) => {
        const lines = part.split("\n");
        let key = lines[0].split(":")[0].trim();
        const content = lines.slice(1).join("\n").trim();

        // Transform the key
        key = key.toLowerCase().replace(/\s+/g, "");

        // Special case for "calltoaction"
        if (key === "calltoaction") {
          key = "call to action";
        }

        acc[key] = content;
        return acc;
      },
      {}
    );

    return NextResponse.json({ script: scriptParts });
  } catch (error: any) {
    console.error("Error generating script:", error);
    return NextResponse.json(
      { error: error.message || "Failed to generate script" },
      { status: 500 }
    );
  }
}
